configure_terminal: true
configure_osx: false

homebrew_installed_packages:
  - bash-completion
  - python
  - git
  - node
  - zsh-history-substring-search
  - mysql

homebrew_cask_apps:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - intellij-idea
  - onedrive
  - rectangle
  - sequel-ace
  - bitwarden

pip_packages:
  - name: pipenv

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV