configure_terminal: true
configure_osx: true

homebrew_installed_packages:
  - bash-completion
  - python
  - git
  - node
  - zsh-history-substring-search
  - poetry
  - awscli

homebrew_cask_apps:
  - docker
  - dropbox
  - jetbrains-toolbox
  - google-chrome
  - onedrive
  - rectangle
  - visual-studio-code
  - bitwarden

pip_packages:
#  - name: pipenv

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV