homebrew_installed_packages:
  - git
  - node
  - bash-completion

homebrew_cask_apps:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - intellij-idea
  - onedrive
  - rectangle


mas_installed_apps:
  - { id: 443987910, name: "1Password" }

pip_packages:
  - name: pipenv

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV